const { withAppBuildGradle } = require('expo/config-plugins')

// Injects a release signingConfig sourced from TROVE_UPLOAD_* properties in
// ~/.gradle/gradle.properties. Lives in a config plugin because /android is
// gitignored and regenerated by `expo prebuild --clean`, so direct edits to
// build.gradle don't survive. Machines without the properties (CI, a fresh
// clone) fall back to the debug keystore and still build.

const RELEASE_SIGNING_CONFIG = `        release {
            if (project.hasProperty('TROVE_UPLOAD_STORE_FILE')) {
                storeFile file(TROVE_UPLOAD_STORE_FILE)
                storePassword TROVE_UPLOAD_STORE_PASSWORD
                keyAlias TROVE_UPLOAD_KEY_ALIAS
                keyPassword TROVE_UPLOAD_KEY_PASSWORD
            }
        }
`

module.exports = function withReleaseSigning(config) {
  return withAppBuildGradle(config, (config) => {
    let gradle = config.modResults.contents
    if (gradle.includes('TROVE_UPLOAD_STORE_FILE')) return config

    // Point the release buildType at the release config when the properties
    // exist. Must run before the signingConfigs insertion below, while the
    // only `release {` blocks in the file are the buildTypes ones.
    gradle = gradle.replace(
      /(release\s\{[^}]*?)signingConfig signingConfigs\.debug/,
      "$1signingConfig project.hasProperty('TROVE_UPLOAD_STORE_FILE') ? signingConfigs.release : signingConfigs.debug"
    )

    gradle = gradle.replace(
      /signingConfigs\s\{\n/,
      `signingConfigs {\n${RELEASE_SIGNING_CONFIG}`
    )

    config.modResults.contents = gradle
    return config
  })
}
