import { Save, Collection } from '../types'

export const MOCK_COLLECTIONS: Collection[] = [
  { id: 'c1', user_id: 'mock', name: 'Design Inspiration', emoji: '✦', color: '#c0613c', description: 'Visual references and design systems', created_at: '2024-01-01T00:00:00Z', save_count: 14 },
  { id: 'c2', user_id: 'mock', name: 'Long Reads', emoji: '◎', color: '#5c7a6e', description: 'Essays and in-depth articles', created_at: '2024-01-02T00:00:00Z', save_count: 27 },
  { id: 'c3', user_id: 'mock', name: 'Dev Tools', emoji: '⌘', color: '#4a5568', description: 'Libraries, tools, and references', created_at: '2024-01-03T00:00:00Z', save_count: 9 },
  { id: 'c4', user_id: 'mock', name: 'Recipes', emoji: '◈', color: '#b87333', description: 'Food and cooking references', created_at: '2024-01-04T00:00:00Z', save_count: 6 },
  { id: 'c5', user_id: 'mock', name: 'Read Later', emoji: '○', color: '#7c6d8a', description: 'Things to get back to', created_at: '2024-01-05T00:00:00Z', save_count: 31 },
]

export const MOCK_SAVES: Save[] = [
  {
    id: '1', user_id: 'mock',
    url: 'https://aeon.co/essays/how-to-think-about-time',
    title: 'How to Think About Time',
    description: 'The deepest puzzles about time have less to do with physics than with the strange temporal structure of conscious experience.',
    type: 'link',
    image_url: 'https://images.unsplash.com/photo-1495364141860-b0d03eccd065?w=600&q=80',
    collection_id: 'c2',
    tags: ['philosophy', 'time'],
    is_inbox: false,
    created_at: '2024-01-15T10:00:00Z',
  },
  {
    id: '2', user_id: 'mock',
    title: 'On constraints and creativity',
    content: 'The best creative work comes from constraints. When you have infinite options, you get paralyzed. Give yourself a box to think inside of. The white page is the enemy; the ruled page is the friend.',
    type: 'note',
    tags: ['creativity', 'writing'],
    is_inbox: false,
    created_at: '2024-01-14T09:30:00Z',
  },
  {
    id: '3', user_id: 'mock',
    url: 'https://linear.app/blog/how-we-built-linear',
    title: 'How We Built Linear: The Product Philosophy',
    description: 'The story behind building Linear, our philosophy on product design, and why we chose to prioritize speed above everything else.',
    type: 'link',
    collection_id: 'c1',
    tags: ['product', 'design'],
    is_inbox: false,
    created_at: '2024-01-13T14:00:00Z',
  },
  {
    id: '4', user_id: 'mock',
    url: 'https://unsplash.com/photos/photo',
    title: 'Minimal Workspace',
    type: 'image',
    image_url: 'https://images.unsplash.com/photo-1484480974693-6ca0a78fb36b?w=600&q=80',
    collection_id: 'c1',
    tags: ['workspace', 'minimal'],
    is_inbox: false,
    created_at: '2024-01-12T11:00:00Z',
  },
  {
    id: '5', user_id: 'mock',
    url: 'https://www.youtube.com/watch?v=example',
    title: 'The Feynman Technique: Learn Anything Faster',
    description: 'Richard Feynman\'s method for mastering any concept by teaching it in simple terms.',
    type: 'video',
    image_url: 'https://images.unsplash.com/photo-1457369804613-52c61a468e7d?w=600&q=80',
    collection_id: 'c2',
    tags: ['learning', 'feynman'],
    is_inbox: false,
    created_at: '2024-01-11T16:00:00Z',
  },
  {
    id: '6', user_id: 'mock',
    url: 'https://github.com/sindresorhus/awesome',
    title: 'Awesome Lists',
    description: 'A curated list of awesome lists covering every topic imaginable.',
    type: 'link',
    collection_id: 'c3',
    tags: ['resources'],
    is_inbox: false,
    created_at: '2024-01-10T08:00:00Z',
  },
  {
    id: '7', user_id: 'mock',
    title: 'Morning pages ritual',
    content: 'Three pages. Every morning. Before coffee, before phone. Just pen on paper, stream of consciousness. Julia Cameron was right about this one.',
    type: 'note',
    tags: ['writing', 'habit'],
    is_inbox: false,
    created_at: '2024-01-09T07:00:00Z',
  },
  {
    id: '8', user_id: 'mock',
    url: 'https://www.figma.com/blog/color-systems',
    title: 'Building a Color System from Scratch',
    description: 'How to design a cohesive color palette that works across light and dark modes, different surfaces, and accessibility requirements.',
    type: 'link',
    image_url: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600&q=80',
    collection_id: 'c1',
    tags: ['design', 'color'],
    is_inbox: false,
    created_at: '2024-01-08T13:00:00Z',
  },
  // Inbox items
  {
    id: '9', user_id: 'mock',
    url: 'https://fs.blog/mental-models',
    title: 'Mental Models: The Best Way to Make Intelligent Decisions',
    description: 'A mental model is simply a representation of how something works. We cannot keep all of the details of the world in our brains.',
    type: 'link',
    tags: [],
    is_inbox: true,
    created_at: '2024-01-16T09:00:00Z',
  },
  {
    id: '10', user_id: 'mock',
    title: 'Ambient music for focus',
    content: 'Brian Eno\'s Music for Airports. Still the gold standard after 45 years. Nothing else comes close for deep work.',
    type: 'note',
    tags: [],
    is_inbox: true,
    created_at: '2024-01-16T15:30:00Z',
  },
  {
    id: '11', user_id: 'mock',
    url: 'https://www.are.na/blog/case-for-research',
    title: 'The Case for Slow Research',
    description: 'Why the best ideas come from sustained, patient attention rather than rapid information consumption.',
    type: 'link',
    image_url: 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=600&q=80',
    tags: [],
    is_inbox: true,
    created_at: '2024-01-16T17:00:00Z',
  },
  {
    id: '12', user_id: 'mock',
    url: 'https://unsplash.com/photos/architecture',
    title: 'Tokyo Side Streets',
    type: 'image',
    image_url: 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=600&q=80',
    tags: [],
    is_inbox: true,
    created_at: '2024-01-16T11:00:00Z',
  },
]
